title: Robert McKee # your name (or website title) here
logo: "/images/round_square.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.robertcmckee.com/portfolio/">Data Science Projects</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/RobertCMcKee/">Resume</a> 
  <br><br>
  <a href="https://www.hackerrank.com/rmckee8">HackerRank</a>
  <br><br>
  <a href="https://www.github.com/rcmckee">GitHub</a>
  <br><br>
  <a href="https://www.linkedin.com/in/RobertCMcKee/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
